### ISSUE TITLE
DB write/crash issues on "stale" AM instances

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2014] opened 2016-02-11 16:05 UTC
4 days in a row, I've come in in the morning to find the copy of AM that I've left open but doing nothing in a bad state.  

If I try to create a new run it fails with the errors -277003 and -3, followed by a 103110:

```
in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMRun_table (id, AMDbObjectType, name, notes, dateTime, facilityId, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMRun]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.
```

If I try to start an XRF scan I get spammed with error -277003 and -3:

```
in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfoSet_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfoSet_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMDetectorInfoSet]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfo_table (id, AMDbObjectType, name, description, units, acquisitionTime, readMode, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMDetectorInfo]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO IDEASXRFScanConfiguration_table (id, AMDbObjectType, name, detectorConfigurations, axisControlInfos, fluorescenceDetector, xrfDetectorInfo, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [IDEASXRFScanConfiguration]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMScan_table (id, AMDbObjectType, name, unEvaluatedName, number, dateTime, endDateTime, runId, samplePre2013, sample, notes, fileFormat, filePath, additionalFilePaths, scanInitialConditions, analyzedDataSourcesConnections, scanConfiguration, currentlyScanning, indexType, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMXRFScan]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMScanAction]: The scan action was unable to store the scan to the database.

in [IDEASXRFScanController]: Could not save XRF data.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfoSet_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMDetectorInfoSet]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfo_table (id, AMDbObjectType, name, description, units, acquisitionTime, readMode, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMDetectorInfo]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO IDEASXRFScanConfiguration_table (id, AMDbObjectType, name, detectorConfigurations, axisControlInfos, fluorescenceDetector, xrfDetectorInfo, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [IDEASXRFScanConfiguration]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMScan_table (id, AMDbObjectType, name, unEvaluatedName, number, dateTime, endDateTime, runId, samplePre2013, sample, notes, fileFormat, filePath, additionalFilePaths, scanInitialConditions, analyzedDataSourcesConnections, scanConfiguration, currentlyScanning, indexType, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row

in [AMXRFScan]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers.

in [AMScanAction]: Could not find the database associated with this scan.
```

Trying to start an XAS scan crashes AM, but I wasn't in debug... The application output read:
```
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMRun_table (id, AMDbObjectType, name, notes, dateTime, facilityId, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMRun]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfoSet_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMDetectorInfoSet]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfo_table (id, AMDbObjectType, name, description, units, acquisitionTime, readMode, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMDetectorInfo]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO IDEASXRFScanConfiguration_table (id, AMDbObjectType, name, detectorConfigurations, axisControlInfos, fluorescenceDetector, xrfDetectorInfo, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [IDEASXRFScanConfiguration]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMScan_table (id, AMDbObjectType, name, unEvaluatedName, number, dateTime, endDateTime, runId, samplePre2013, sample, notes, fileFormat, filePath, additionalFilePaths, scanInitialConditions, analyzedDataSourcesConnections, scanConfiguration, currentlyScanning, indexType, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMXRFScan]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMScanAction]: The scan action was unable to store the scan to the database. (code 103106)" 
Serious: "in [IDEASXRFScanController]: Could not save XRF data. (code -1)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfoSet_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMDetectorInfoSet]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMControlInfoList_table (id, AMDbObjectType, name, description, thumbnailCount) VALUES (?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMControlInfoList]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMDetectorInfo_table (id, AMDbObjectType, name, description, units, acquisitionTime, readMode, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMDetectorInfo]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO IDEASXRFScanConfiguration_table (id, AMDbObjectType, name, detectorConfigurations, axisControlInfos, fluorescenceDetector, xrfDetectorInfo, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [IDEASXRFScanConfiguration]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMScan_table (id, AMDbObjectType, name, unEvaluatedName, number, dateTime, endDateTime, runId, samplePre2013, sample, notes, fileFormat, filePath, additionalFilePaths, scanInitialConditions, analyzedDataSourcesConnections, scanConfiguration, currentlyScanning, indexType, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMXRFScan]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMScanAction]: Could not find the database associated with this scan. (code 103110)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMLoopActionInfo3_table (id, AMDbObjectType, name, shortDescription, longDescription, iconFileName, expectedDuration, canCopy, loopCount, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMLoopActionInfo3]: Could not store to db (actions), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMActionLog3_table (id, AMDbObjectType, name, startDateTime, endDateTime, finalState, info, longDescription, iconFileName, parentId, actionInheritedLoop, failureMessage, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMActionLog3]: Could not store to db (actions), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Alert: "in [AMActionRunner3]: There was a problem logging the uncompleted action to your database.  Please report this problem to the Acquaman developers. (code -200)" 
Alert: "in [AMDatabase]: database save failed. Could not execute query (INSERT OR REPLACE INTO AMExporterOptionGeneralAscii_table (id, AMDbObjectType, name, fileName, headerText, headerIncluded, columnHeader, columnHeaderIncluded, columnHeaderDelimiter, sectionHeader, sectionHeaderIncluded, includeAllDataSources, includeHigherDimensionSources, firstColumnOnly, separateHigherDimensionalSources, higherDimensionsInRows, dataSources, dataSourceOrganizeModes, dataSourceIsRequired, dataSourceOmitAxisValueColumns, separateSectionFileName, columnDelimiter, newlineDelimiter, thumbnailCount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)). The SQL reply was: unable to open database file Unable to fetch row (code -3)" 
Alert: "in [AMExporterOptionGeneralAscii]: Could not store to db (user), the insert or update call failed. Please report this problem to the Acquaman developers. (code -277003)" 
Serious: "AMCDFDataStore: Could not create file '/AcquamanLocalData/ideas/users/Commissioning/userData/2016/02/Thu_02_11_10_02_48_7654.cdf' for the CDF data store. Maybe the file exists already? The CDF data store is now invalid. (code -101)" 
Debug: "AMCDFDataStore: Could not create axis values CDF variable for axis 'eV'. The CDF error was: -2053 (code -724)" 
Debug: "AMCDFDataStore: could not set attribute Axis::Name for axis info. (code -1003)" 
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'I_0'. The CDF error was: -2053. (code -102)" 
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'Sample'. The CDF error was: -2053. (code -102)" 
Debug: "AMCDFDataStore: Could not create CDF variable for measurement 'Reference'. The CDF error was: -2053. (code -102)" 

GLib-ERROR **: Cannot create pipe main loop wake-up: Too many open files

aborting...
```

**Comment by epengr** [comment] 2016-02-11 16:07
The issue is resolved by restarting.

**Comment by iainworkman** [comment] 2016-02-12 14:28
This is a duplicate of #2015, which seems to be resolved by a fix I will attempt to deploy today.
Closing out.

**Closed by iainworkman** 2016-02-12 14:28 UTC
Labels: Bug, Crash
