### ISSUE TITLE
Clean Up SamplePre2013 warning in upgraded SGM application

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/acquaman#1717] opened 2015-11-16 17:00 UTC
We're not using the sample system anymore, so we should see if we can get that warning to go away.

**Comment by dretrex** [comment] 2015-11-16 17:01
Only REIXS uses it at all if I recall correctly. All the applications have been getting this error mon for years.

Sent from my iPhone

On Nov 16, 2015, at 9:00 AM, davidChevrier <notifications@github.com<mailto:notifications@github.com>> wrote:


We're not using the sample system anymore, so we should see if we can get that warning to go away.

-

**Comment by iainworkman** [comment] 2015-11-19 14:27
When does this error appear, as I'm not getting it on startup?

**Comment by davidChevrier** [comment] 2015-11-19 15:47
When you run a scan.

**Comment by dretrex** [comment] 2015-11-27 04:53
I am also unable to reproduce this.  I'm going to close this issue until it resurfaces itself.

**Closed by dretrex** 2015-11-27 04:53 UTC
Labels: BL - SGM

**Comment by dretrex** [comment] 2015-11-27 04:58
Clarification, it is only a Debug error mon so it wouldn't be noticeable to a user.
