### ISSUE TITLE
SGM commission tool messes up SR570 behaviour

### ISSUE THREAD

**Issue by regiert** [acquaman/acquaman#1621] opened 2015-09-21 20:21 UTC
The SR570 gain settings don't work when there is a SGM commissioning tool running.  I've checked the SR570 gain settings with both the EDM interface and the original SGMAcquaman and they are fine.  When I run the commissioning tool, the gains are no longer setting properly with either the commissioning tool interface or the original SGMAcquaman.  When I close the commissioning tool, normal behaviour is recovered.

**Comment by iainworkman** [comment] 2015-09-30 16:10
@XuetaoLiu-CLS I believe that the solution to this issue is a deployment of a scalar coordinator which you worked on. Is that correct? If this is the case could you let me know what would be required to integrate this into SGM? I would like to have this more robust solution implemented on the new SGM Acquaman.

**Comment by iainworkman** [comment] 2016-01-27 16:41
Is this a duplicate of #1776  #1802 and #1822

**Comment by dretrex** [comment] 2016-01-27 17:57
There does appear to be a bunch of duplicates of this issue.  Also, how relevant is this issue since the commissioning tool won't be used anymore (right?)?

**Comment by iainworkman** [comment] 2016-01-27 18:04
I think we'll need to investigate whether this is genuinely related to the commissioning tool. With regard to continued use of the commissioning tool, I think this needs discussion. I know some users have made use of it, as I think it offers things not available for a fast scan (higher resolution, the QE65000) . If so I think there needs to be an issue created for making it more production ready (eg. changing its name to step scan, customizing the controls and detectors it has available to it). My guess is this will eventually involve a SGMStepScan subclass, if Tom elects for it to remain.

**Closed** 2016-06-08 15:34 UTC
Labels: BL - SGM
